[2019-02-10 19:14:38,638] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-06T00:00:00+00:00 [queued]>
[2019-02-10 19:14:38,643] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Data_to_SQL 2015-06-06T00:00:00+00:00 [queued]>
[2019-02-10 19:14:38,643] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2019-02-10 19:14:38,652] {models.py:1593} INFO - Executing <Task(BashOperator): Data_to_SQL> on 2015-06-06T00:00:00+00:00
[2019-02-10 19:14:38,652] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Data_to_SQL 2015-06-06T00:00:00+00:00 --job_id 43 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmp1gqsge9m']
[2019-02-10 19:14:39,178] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL [2019-02-10 19:14:39,178] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 19:14:39,327] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL [2019-02-10 19:14:39,327] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 19:14:39,339] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL [2019-02-10 19:14:39,339] {cli.py:520} INFO - Running <TaskInstance: Rescale.Data_to_SQL 2015-06-06T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 19:14:39,348] {models.py:1788} ERROR - /home/ec2-user/insert_to_sql.sh
Traceback (most recent call last):
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1642, in _run_raw_task
    self.render_templates()
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1998, in render_templates
    rendered_content = rt(attr, content, jinja_context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 2907, in render_template
    return jinja_env.get_template(content).render(**context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /home/ec2-user/insert_to_sql.sh
[2019-02-10 19:14:39,350] {models.py:1817} INFO - All retries failed; marking task as FAILED
[2019-02-10 19:14:39,362] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL Traceback (most recent call last):
[2019-02-10 19:14:39,362] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/bin/airflow", line 32, in <module>
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     args.func(args)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     return f(*args, **kwargs)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     _run(args, dag, ti)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     pool=args.pool,
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     return func(*args, **kwargs)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1642, in _run_raw_task
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     self.render_templates()
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1998, in render_templates
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     rendered_content = rt(attr, content, jinja_context)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 2907, in render_template
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     return jinja_env.get_template(content).render(**context)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     return self._load_template(name, self.make_globals(globals))
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     template = self.loader.load(self, name, globals)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     source, filename, uptodate = self.get_source(environment, name)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL     raise TemplateNotFound(template)
[2019-02-10 19:14:39,363] {base_task_runner.py:101} INFO - Job 43: Subtask Data_to_SQL jinja2.exceptions.TemplateNotFound: /home/ec2-user/insert_to_sql.sh
[2019-02-10 19:14:43,638] {logging_mixin.py:95} INFO - [2019-02-10 19:14:43,638] {jobs.py:2527} INFO - Task exited with return code 1
